[package]
name = "Rust"
version = "0.1.0"
authors = ["Emanuele Manzione <m4nu.91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "unity_rust"
crate-type = ["dylib"]

[dependencies]
rand = "0.7.0"